package com.liu.community.mapper;

import com.liu.community.model.Nottification;
import com.liu.community.model.NottificationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NottificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    long countByExample(NottificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int deleteByExample(NottificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int insert(Nottification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int insertSelective(Nottification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    List<Nottification> selectByExampleWithRowbounds(NottificationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    List<Nottification> selectByExample(NottificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    Nottification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Nottification record, @Param("example") NottificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int updateByExample(@Param("record") Nottification record, @Param("example") NottificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int updateByPrimaryKeySelective(Nottification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nottification
     *
     * @mbg.generated Wed Mar 18 14:35:37 CST 2020
     */
    int updateByPrimaryKey(Nottification record);
}